@startmindmap 功能架構圖
<style>
mindmapDiagram{
    .blue *{
        BackgroundColor #84C1FF
    }

    .green *{
        BackgroundColor #96FED1
    }

    .red *{
        BackgroundColor #FF5151
    }
}
</style>

+ 線上投票平台

++ 登入/註冊 <<blue>>
+++ 登入
++++ 提交帳號/信箱、密碼
++++ 檢查帳號/信箱存在
++++ 檢查密碼正確
+++ 註冊
++++ 提交名稱、帳號、信箱、密碼
++++ 檢查帳號被使用
++++ 檢查信箱被使用
++++ 檢查密碼
+++++_ 密碼長度是否 > 8
+++++_ 密碼需英文大小寫且包含數字，但不包含特殊字元
+++ 第三方驗證
++++_ facebook
++++_ google
+++ 忘記密碼
++++ 信箱驗證

-- 活動 <<green>>
--- 搜尋(非用戶也可觀看)
---- 預覽活動介紹
---- 關鍵字搜尋
---- 類型過濾
----- 活動狀態
------_ 進行中
------_ 尚未進行
------_ 已結束
----- 投票類型
------_ 單選
------_ 多選
--- 投票
---- 預覽投票內容
---- 更新票數
----- 送出
----- 撤回
---- 預覽投票結果(需建立者授權)
--- 留言(限有投票的人和建立者)
---- 編輯普通文字
---- 回覆
---- 刪除
--- 建立
---- 編輯標題
---- 編輯介紹內容
----- 編輯文字
-----_ 普通、粗體、斜體
-----_ 嵌入連結
-----_ 子標題
-----_ 嵌入圖片
----- 編輯列表
------_ 有序
------_ 無序
---- 編輯項目
----- 新增
----- 刪除
----- 更新
---- 選擇投票類型
-----_ 單選
-----_ 多選
---- 授權是否預覽結果
--- 更新(只在活動開始前)
---- 刪除

++ 使用者資訊 <<red>>
+++ 修改帳號
++++ 信箱通知驗證碼
+++ 修改密碼
++++ 信箱通知驗證碼
+++ 修改信箱
++++ 信箱通知驗證碼
+++ 更新頭像
+++ 更新名稱
+++ 刪除帳號
++++ 信箱通知驗證碼

@endmindmap